// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdyb34pYESHq9Ix1VGYHVf7rVybDVLw3I',
    appId: '1:128351405706:web:4e095203f5714febad0f73',
    messagingSenderId: '128351405706',
    projectId: 'pace-841e7',
    authDomain: 'pace-841e7.firebaseapp.com',
    storageBucket: 'pace-841e7.firebasestorage.app',
    measurementId: 'G-QKHTKSX8H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLDebFKTjPfY5igPE9rKBlF7ezsUpuxt0',
    appId: '1:128351405706:android:377776827f54c717ad0f73',
    messagingSenderId: '128351405706',
    projectId: 'pace-841e7',
    storageBucket: 'pace-841e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsF0UI6TZE0wdIT5bOlIOpks8n_eRssiA',
    appId: '1:128351405706:ios:540c11e586459927ad0f73',
    messagingSenderId: '128351405706',
    projectId: 'pace-841e7',
    storageBucket: 'pace-841e7.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsF0UI6TZE0wdIT5bOlIOpks8n_eRssiA',
    appId: '1:128351405706:ios:540c11e586459927ad0f73',
    messagingSenderId: '128351405706',
    projectId: 'pace-841e7',
    storageBucket: 'pace-841e7.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdyb34pYESHq9Ix1VGYHVf7rVybDVLw3I',
    appId: '1:128351405706:web:768247cbbe65af3aad0f73',
    messagingSenderId: '128351405706',
    projectId: 'pace-841e7',
    authDomain: 'pace-841e7.firebaseapp.com',
    storageBucket: 'pace-841e7.firebasestorage.app',
    measurementId: 'G-YNBKFZZQ99',
  );
}
